version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: bank-postgres
    environment:
      POSTGRES_DB: bank
      POSTGRES_USER: bankUser
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
